stages:
  - deploy
Deploy:
  stage: deploy
  before_script:
  - 'command -v ssh-agent &gt;/dev/null || ( apk add --update openssh )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $EC2_IPADDRESS &gt;&gt; ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - zip -r public.zip public
    - scp -o StrictHostKeyChecking=no public.zip ubuntu@35.92.11.154:/var/www/html
    - ssh -o StrictHostKeyChecking=no ubuntu@35.92.11.154 "cd /var/www/html; touch foo.txt; unzip public.zip"