import mongoose from "mongoose"
const ingredientSchema=new mongoose.Schema({
    IngredientID:{
        type:String
    },
    IngredientName:{
        type:String
    },
    Description:{
        type:String
    },
    Expiry:{
        type:String
    },
    UnitofMeasurement:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'mu'
    },
    UnitPrice:{
        type:Number
    },
    supplierId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Supplier'
    },
    CurrentStock:{
        type:Number
    },
    ThresholdLevel:{
        type:String
    },
    Allergens:{
        type:String
    },
    ShelfLife:{
        type:String
    },
    StorageInstructions:{
        type:String
    },
    CategoryType:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'ingredientCategoryModel'
    },
    Alternative:{
        type:String
    },
    NutritionalInformation:{
        type:String
    },
    Notes:{
        type:String
    },
    Active:{
        type:Boolean
    },
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:'user'
    }
},{timestamps:true})
const IngredientsModel=mongoose.model("ingredientsModel",ingredientSchema)
export default IngredientsModel
